//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMApr2023Batch_CASProj.Models.SecurityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman
    {
        public int SalesmanId { get; set; }
        public string SalesmanFirstName { get; set; }
        public string SalesmanLastName { get; set; }
        public string SalesmanDescription { get; set; }
        public string SalesmanEmail { get; set; }
        public string SalesmanPhone { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
